const BAD_REQUEST = 400;
const INTERNAL_SERVERE_ERROR = 500;
const NOT_FOUND = 404;
const OWNER_ERROR = 403;
const CONFLICT_ERROR = 409;
const UNAUTHORIZED_ERROR = 401;

module.exports = {
  BAD_REQUEST,
  INTERNAL_SERVERE_ERROR,
  NOT_FOUND,
  OWNER_ERROR,
  CONFLICT_ERROR,
  UNAUTHORIZED_ERROR,
};
